# Generated by Django 3.1.7 on 2023-04-10 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('host', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='members',
            name='cpu_usage',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
