# Generated by Django 3.1.7 on 2023-04-11 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('host', '0004_remove_members_cores'),
    ]

    operations = [
        migrations.CreateModel(
            name='all_users_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('host', models.CharField(max_length=255)),
                ('cores', models.IntegerField(default=1)),
                ('cpu_usage', models.IntegerField()),
            ],
        ),
    ]
