# Generated by Django 3.1.7 on 2023-04-11 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('host', '0007_auto_20230411_1741'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='all_users_data',
            name='n_threads',
        ),
    ]
