# Generated by Django 3.1.7 on 2023-04-11 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('host', '0008_remove_all_users_data_n_threads'),
    ]

    operations = [
        migrations.AddField(
            model_name='all_users_data',
            name='program_name',
            field=models.CharField(default=1, max_length=40),
            preserve_default=False,
        ),
    ]
