# Generated by Django 3.1.7 on 2023-04-21 22:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('host', '0009_all_users_data_program_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='all_users_data',
            name='data',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
