# Generated by Django 3.1.7 on 2023-04-21 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('host', '0010_all_users_data_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='all_users_data',
            name='data',
            field=models.DateField(),
        ),
    ]
