# Generated by Django 3.1.7 on 2023-04-21 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('host', '0011_auto_20230422_0103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='all_users_data',
            name='data',
            field=models.CharField(max_length=255),
        ),
    ]
