# Generated by Django 3.1.7 on 2023-04-23 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('host', '0014_auto_20230423_2145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='all_users_data',
            name='data',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
