# Generated by Django 3.1.7 on 2023-04-23 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('host', '0015_auto_20230423_2147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='all_users_data',
            name='program_id',
            field=models.CharField(max_length=255),
        ),
    ]
