# Generated by Django 3.1.7 on 2023-04-23 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('host', '0016_auto_20230423_2218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='all_users_data',
            name='cpu_usage',
            field=models.FloatField(),
        ),
    ]
