# Generated by Django 3.1.7 on 2023-04-23 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('host', '0017_auto_20230423_2226'),
    ]

    operations = [
        migrations.CreateModel(
            name='agents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=15)),
            ],
        ),
    ]
