# Generated by Django 3.1.7 on 2023-04-23 20:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('host', '0018_agents'),
    ]

    operations = [
        migrations.AddField(
            model_name='agents',
            name='owner_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='agents',
            name='owner_surname',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
    ]
